name: add-label-customer-submission.yaml
on:
  issues:
    types:
      - opened
env:
  MEMBER_LIST: ${{ secrets.SENZING_MEMBERS }}
  CREATOR: ${{ github.actor }}
jobs:
  automate-issues-labels:
    name: Add customer-submission label
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        env:
          BOOL: ${{ contains( env.MEMBER_LIST, env.CREATOR ) }}
        if: ${{ env.BOOL == 'false' }}
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "customer-submission"
